ComputerTomography \
  --type-space-x "lp"  \
  --px 2  \
  --type-space-y "lp"  \
  --py 2  \
  --powery 2  \
  --delta 0.01  \
  --maxiter 50 \
  --noise-level 0.01 \
  --num-angles 40 \
  --num-offsets 41 \
  --num-pixels-x 41 \
  --num-pixels-y 41 \
  --solution solution.mat \
  --phantom ${CMAKE_CURRENT_SOURCE_DIR}/pre/phantom.mat
